services:
  backend:
    image: securechat-backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    image: securechat-frontend:latest
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
